name: Actions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v4

      - name: 🛠 Set up Python 3
        uses: actions/setup-python@v4
        id: python
        with:
          python-version: 3.x
          cache: "pip"

      - name: 📦 Install dependencies
        run:  scripts/setup

      - name: 🖤 Lint with Black
        run:  black . --check

  test:
    name: Test with Python ${{ matrix.python-version }}
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: 🛠️ Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: 📦 Install dependencies
        run:  scripts/setup

      - name: 🏃 Run tests
        run:  scripts/test

      - name: 📤 Upload coverage to Codecov
        if: ${{ matrix.python-version == '3.8' }}
        run: |
          scripts/coverage
          curl -sfSL https://codecov.io/bash | bash -