name: Release

on:
  release:
    types:
      - published

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.12"

      - name: Set version number
        run: |
          sed -i "s|main|${{ github.event.release.tag_name }}|" ./pyproject.toml
          cat ./pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Package
        run: python -m build

      - name: Upload dists
        uses: actions/upload-artifact@v4.6.2
        with:
          name: "dist"
          path: "dist/"
          if-no-files-found: error
          retention-days: 3

  publish:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: release
      url: https://pypi.org/p/pyaftership
    permissions:
      attestations: write
      contents: write
      id-token: write
    steps:
      - name: Download dists
        uses: actions/download-artifact@v5.0.0
        with:
          name: "dist"
          path: "dist/"

      - name: Publish dists to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0

      - name: Attest
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a #v3.0.0
        with:
          subject-path: dist/*

      - name: Upload release assets
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
        with:
          files: dist/*
