name: Release

on:
  release:
    types:
      - published

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.12"

      - name: Set version number
        run: |
          sed -i "s|main|${{ github.event.release.tag_name }}|" ./setup.py
          cat ./setup.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Package
        run: python setup.py sdist bdist_wheel

      - name: Upload dists
        uses: actions/upload-artifact@v4.6.1
        with:
          name: "dist"
          path: "dist/"
          if-no-files-found: error
          retention-days: 3

  publish:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: release
      url: https://pypi.org/p/pyaftership
    permissions:
      attestations: write
      contents: write
      id-token: write
    steps:
      - name: Download dists
        uses: actions/download-artifact@v4.1.9
        with:
          name: "dist"
          path: "dist/"

      - name: Publish dists to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4

      - name: Attest
        uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 #v2.2.3
        with:
          subject-path: dist/*

      - name: Upload release assets
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          files: dist/*
